---
# Playbook to undeploy Airtrail and its components
- name: Undeploy Airtrail from GKE
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete Airtrail deployment
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: airtrail-deployment
        namespace: default

    - name: Delete Airtrail service (if exists)
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: airtrail-service
        namespace: default
      ignore_errors: true

    - name: Wait for service to be removed
      kubernetes.core.k8s_info:
        kind: Service
        name: airtrail-service
        namespace: default
      register: service_list
      until: service_list.resources | length == 0
      retries: 20
      delay: 10

    - name: Wait for pods to be removed
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
        label_selectors:
          - app=airtrail-app
      register: pod_list
      until: pod_list.resources | length == 0
      retries: 10
      delay: 5

    - name: Confirm undeployment
      debug:
        msg: "Airtrail has been successfully undeployed from the cluster"

    - name: Delete PostgreSQL PVC
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: PersistentVolumeClaim
        name: airtrail-db-pvc
        namespace: default
      when: delete_data is defined and delete_data == "true"

    - name: Delete PostgreSQL deployment
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: airtrail-db-deployment
        namespace: default
      when: delete_data is defined and delete_data == "true"

    - name: Delete PostgreSQL service
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: airtrail-db-service
        namespace: default
      when: delete_data is defined and delete_data == "true"
